name: myCICD-workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: we are testing this  workflow
        run: echo Hellow everyone!
